### ISSUE TITLE
Get contacts of other users

### ISSUE THREAD

**Issue by HrishitaV** [jasonjoh/ruby_outlook#10]
This is in continuation to https://github.com/jasonjoh/ruby_outlook/issues/9
Thanks for your response. I added the mentioned scope in my code and the 'ErrorAccessDenied' is not coming now however, now another error is coming-
URI:https://outlook.office365.com/api/v2.0/users/woojin_cho_test@xxxx.onmicrosoft.com/Contacts?%24top=5&%24skip=0>, :response_headers=>{"content-type"=>"application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8", "x-rum-validated"=>"1", "x-beserver"=>"BN7PR11MB2708", "connection"=>"close", "request-id"=>"57177d64-7f14-4930-8744-8e09a211bdbf", "x-powered-by"=>"ASP.NET", "rate-limit-limit"=>"10000", "x-feserver"=>"BN6PR1801CA0030, MWHPR15CA0060, SG2PR06CA0113", "date"=>"Tue, 17 Apr 2018 04:51:16 GMT", "x-aspnet-version"=>"4.0.30319", "x-backendhttpstatus"=>"404, 404, 404", "set-cookie"=>"exchangecookie=f191dd8a2bd347df9eefe3ad542fce7a; expires=Wed, 17-Apr-2019 04:51:16 GMT; path=/; HttpOnly", "transfer-encoding"=>"chunked", "client-request-id"=>"f445d0ce-41fa-11e8-afc2-080027be5d02", "x-calculatedfetarget"=>"MWHPR15CU003.internal.outlook.com, BN6PR1801CU002.internal.outlook.com", "x-feproxyinfo"=>"MWHPR15CA0060.NAMPRD15.PROD.OUTLOOK.COM, BN6PR1801CA0030.NAMPRD18.PROD.OUTLOOK.COM", "odata-version"=>"4.0", "rate-limit-remaining"=>"9998", "rate-limit-reset"=>"2018-04-17T04:56:59.942Z", "x-diaginfo"=>"BN7PR11MB2708", "server"=>"Microsoft-IIS/10.0", "cache-control"=>"private", "x-calculatedbetarget"=>"BN7PR11MB2708.namprd11.prod.outlook.com", "x-ms-appid"=>"3e216d74-c081-4cf0-8abd-500ac41d21f4"}, :ssl=>{}}, @on_complete_callbacks=[]>"
"------------------contact response-------{"ruby_outlook_response":{"error":{"message":"The specified folder could not be found in the store.","code":"ErrorFolderNotFound"}},"ruby_outlook_error":404}"
"------------------contacts before refresh {"ruby_outlook_error"=>404, "ruby_outlook_response"=>{"error"=>{"message"=>"The specified folder could not be found in the store.", "code"=>"ErrorFolderNotFound"}}} and Hash"
"------------------contacts ruby_outlook_error404ruby_outlook_responseerrormessageThe specified folder could not be found in the store.codeErrorFolderNotFound"

The user for sure has a contact in the Contact folder.

Could you please guide further.

Note: Have removed the host name from the URI. Actually it is going fine.

**Comment by jasonjoh** [comment]
Closing this as out of scope. See https://developer.microsoft.com/graph/support for support options.
