### ISSUE TITLE
Get only delta contacts

### ISSUE THREAD

**Issue by HrishitaV** [jasonjoh/ruby_outlook#11]
Is there a way we can get only the new/delta contacts of an user. Like there is an user 'A' who has contacts - {C, D, E, F, G} out of which {C & D} were already pulled. Is there a way in next request we can pull only {E, F, G}

**Comment by jasonjoh** [comment]
The Outlook REST API supports this (https://msdn.microsoft.com/en-us/office/office365/api/contacts-rest-operations#synchronize-contacts-and-contact-folders), or even better, the Microsoft Graph API (https://developer.microsoft.com/en-us/graph/docs/concepts/delta_query_overview). This library doesn't implement a function for it, but you can extend it to do so if you want.
