### ISSUE TITLE
Outdates files on RubyGems.org

### ISSUE THREAD

**Issue by nvanselow** [jasonjoh/ruby_outlook#3]
Thanks for the great wrapper around the Microsoft 365 API. I was initially having issues, but discovered the gem installed from rubygems.org had old code (References to 1.0 API); however, your code on Github works perfectly. Would you mind updating the Gem published on rubygems.org with the most recent code?

Thanks in advance.

**Comment by jasonjoh** [comment]
I'll have a look as soon as I can. Sorry for the confusion.

**Comment by jasonjoh** [comment]
I just pushed a new version with the latest. See https://rubygems.org/gems/ruby_outlook/versions/0.2.0

**Comment by nvanselow** [comment]
Awesome. Thank you for your quick responses!
