### ISSUE TITLE
Get contacts of other users

### ISSUE THREAD

**Issue by HrishitaV** [jasonjoh/ruby_outlook#9]
The get_contacts method gives the flexibility to pass the user(other than the logged in user) whose contacts are suppose to be fetched.
Using that method and the request URL formed is '/api/v2.0/users/woojin_cho_test@mckinseyandcompany.onmicrosoft.com/Contacts'
Logged in with an Admin user but not able to get the contacts of this user. Getting the below error message-
{\"ruby_outlook_response\":{\"error\":{\"message\":\"Access is denied. Check credentials and try again.\",\"code\":\"ErrorAccessDenied\"}},\"ruby_outlook_error\":403}
reason=\\\"The token contains not enough scope to make this delegate access 

:body=>\"{\\\"error\\\":{\\\"code\\\":\\\"ErrorAccessDenied\\\",\\\"message\\\":\\\"Access is denied. Check credentials and try again.\\\"}}\", :url=>#<Addressable::URI:0xfda709108 URI:https://outlook.office365.com/api/v2.0/users/woojin_cho_test@mckinseyandcompany.onmicrosoft.com/Contacts?%24top=5&%24skip=0>, :response_headers=>{\"rate-limit-limit\"=>\"10000\", \"date\"=>\"Fri, 13 Apr 2018 09:50:16 GMT\", \"cache-control\"=>\"private\", \"transfer-encoding\"=>\"chunked\", \"x-calculatedbetarget\"=>\"BN7PR11MB2708.namprd11.prod.outlook.com\", \"x-rum-validated\"=>\"1\", \"x-ms-diagnostics\"=>\"2000008;reason=\\\"The token contains not enough scope to make this delegate access call.\\\";error_category=\\\"invalid_grant\\\"\", \"odata-version\"=>\"4.0\", \"content-type\"=>\"application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8\", \"client-request-id\"=>\"118b301e-3f00-11e8-8242-080027be5d02\", \"set-cookie\"=>\"exchangecookie=679971feedbe42acb6f380b199474b78; expires=Sat, 13-Apr-2019 09:50:17 GMT; path=/; HttpOnly\", \"www-authenticate\"=>\"Bearer client_id=\\\"00000002-0000-0ff1-ce00-000000000000\\\", trusted_issuers=\\\"00000001-0000-0000-c000-000000000000@*\\\", token_types=\\\"app_asserted_user_v1 service_asserted_app_v1\\\", error=\\\"invalid_token\\\"\", \"x-feserver\"=>\"BN6PR1801CA0036, MWHPR11CA0047, SG2PR06CA0103\", \"server\"=>\"Microsoft-IIS/10.0\", \"rate-limit-remaining\"=>\"9999\", \"x-powered-by\"=>\"ASP.NET\", \"connection\"=>\"close\", \"x-backendhttpstatus\"=>\"403, 403, 403\", \"rate-limit-reset\"=>\"2018-04-13T10:00:17.337Z\", \"x-ms-appid\"=>\"3e216d74-c081-4cf0-8abd-500ac41d21f4\", \"x-aspnet-version\"=>\"4.0.30319\", \"x-diaginfo\"=>\"BN7PR11MB2708\", \"x-beserver\"=>\"BN7PR11MB2708\", \"request-id\"=>\"95881846-45e8-403d-a7dd-a554d82eb118\", \"x-calculatedfetarget\"=>\"MWHPR11CU002.internal.outlook.com, BN6PR1801CU002.internal.outlook.com\", \"x-feproxyinfo\"=>\"MWHPR11CA0047.NAMPRD11.PROD.OUTLOOK.COM, BN6PR1801CA0036.NAMPRD18.PROD.OUTLOOK.COM\"}, :ssl=>{}}, @on_complete_callbacks=[]>"

Could you please help.

**Comment by jasonjoh** [comment]
That's a problem with your token, not this library. This will not work unless the user you are logged in with has delegate access to the woojin_cho_test account's contacts, and you must include the `Contacts.Read.Shared` scope in your auth request.

**Comment by HrishitaV** [comment]
Just to add.. the user has a contact in the Contacts folder.
